services:
  - type: web
    name: gestor-turnos
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gestor-turnos-db
          property: connectionString

databases:
  - name: gestor-turnos-db
    plan: free
